language: bash

sudo: required

install:
  - sudo add-apt-repository -y ppa:avsm/ocaml42+opam12
  - sudo apt-get update -qq
  - sudo apt-get install -qq ocaml opam
  - export OPAMYES=1 && opam init && eval `opam config env`
  - opam install core core_kernel oasis ounit re2
  - oasis setup
  - ocaml setup.ml -configure --enable-tests

script:
  - make test
